using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;
using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.Lionbridge.DataSourceHandlers.EnumDataHandlers;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{

    public IEnumerable<DataSourceItem> GetData()
    {
        return new List<DataSourceItem>()
        {
            new("aa-ET", "Afar" ),
            new("ab-GE", "Abkhaz [Abkhazian]" ),
            new("ach-UG", "Acholi [Acoli]" ),
            new("ADH", "Adhola (Uganda)" ),
            new("af-ZA", "Afrikaans" ),
            new("ak-GH", "Akan" ),
            new("alg-CA", "Algonquin" ),
            new("am-ET", "Amharic" ),
            new("apa-us", "Apache" ),
            new("ar-AE", "Arabic (United Arab Emirates)" ),
            new("ar-DZ", "Arabic (Algeria)" ),
            new("ar-EG", "Arabic (Egypt)" ),
            new("ar-IL", "Arabic (Israel)" ),
            new("ar-IQ", "Arabic (Iraq)" ),
            new("ar-JO", "Arabic (Jordan)" ),
            new("ar-KW", "Arabic (Kuwait)" ),
            new("AR-LB", "Arabic (Lebanon)" ),
            new("ar-LY", "Arabic (Libya)" ),
            new("ar-MA", "Arabic (Morocco)" ),
            new("arn-CL", "Mapudungun" ),
            new("ar-OM", "Arabic (Oman)" ),
            new("ar-qa", "Arabic (Qatar)" ),
            new("ar-SA", "Arabic (Saudi Arabia)" ),
            new("ar-SD", "Arabic (Sudan)" ),
            new("ar-TN", "Arabic (Tunisia)" ),
            new("ar-xg", "Arabic (Gulf)" ),
            new("ar-XN", "Arabic (International) [Modern Standard]" ),
            new("as-IN", "Assamese" ),
            new("az-AZ", "Azerbaijani" ),
            new("az-Latn-AZ", "Azerbaijani (Latin)" ),
            new("bal-PK", "Balochi" ),
            new("ban-IN", "Bali [Balinese]" ),
            new("ba-RU", "Bashkir" ),
            new("be-BY", "Belarusan [Belarusian]" ),
            new("ber-MA", "Tamazight [Berber]" ),
            new("bfy-IN", "Bagheli" ),
            new("bg-BG", "Bulgarian" ),
            new("bhb-IN", "Bhili" ),
            new("bh-IN", "Bhojpuri" ),
            new("bih-in", "Bihari" ),
            new("bin-NG", "Edo [Bini]" ),
            new("bi-VU", "Bislama" ),
            new("bn-BD", "Bengali [Bangla]" ),
            new("bn-IN", "Bengali (India)" ),
            new("bo-CN", "Tibetan" ),
            new("br-FR", "Breton" ),
            new("brx-IN", "Bodo" ),
            new("bs-BA", "Bosnian" ),
            new("bs-Cyrl-BA", "Bosnian (Cyrillic)" ),
            new("bs-Latn-BA", "Bosnian (Latin)" ),
            new("ca-ES", "Catalan" ),
            new("ca-ES-V", "Valencian" ),
            new("ceb-PH", "Cebuano" ),
            new("chk-FM", "Chuukese [Trukese]" ),
            new("co-FR", "Corsican (France)" ),
            new("co-IT", "Corsican (Italy)" ),
            new("cr-CA", "Cree" ),
            new("cs-CZ", "Czech" ),
            new("cy-GB", "Welsh" ),
            new("da-DK", "Danish" ),
            new("de-at", "German (Austria)" ),
            new("de-BE", "German (Belgium)" ),
            new("de-ch", "German (Switzerland)" ),
            new("de-de", "German (Germany)" ),
            new("de-li", "German (Liechtenstein)" ),
            new("de-lu", "German (Luxembourg)" ),
            new("dua-CM", "Duala" ),
            new("dv-MV", "Dhivehi [Maldivian]" ),
            new("dyu-BF", "Dyula" ),
            new("dz-BT", "Dzongkha [Bhutanese]" ),
            new("ee-GH", "Ewe" ),
            new("el-CY", "Greek (Cyprus)" ),
            new("el-GR", "Greek" ),
            new("en-au", "English (Australia)" ),
            new("en-bz", "English (Belize)" ),
            new("en-ca", "English (Canada)" ),
            new("en-cpe", "Creoles and pidgins, English-based (Other)" ),
            new("en-cy", "English (Cyprus)" ),
            new("en-EG", "English (Egypt)" ),
            new("en-gb", "English (United Kingdom)" ),
            new("en-HK", "English (Hong Kong)" ),
            new("en-id", "English (Indonesia)" ),
            new("en-ie", "English (Ireland)" ),
            new("en-IN", "English (India)" ),
            new("en-jm", "English (Jamaica)" ),
            new("en-JO", "English (Jordan)" ),
            new("en-KE", "English (Kenya)" ),
            new("en-LB", "English (Lebanon)" ),
            new("en-LK", "English (Sri Lanka)" ),
            new("en-MT", "English (Malta)" ),
            new("en-MW", "English (Malawi)" ),
            new("en-MY", "English (Malaysia)" ),
            new("en-NG", "English (Nigeria)" ),
            new("en-nz", "English (New Zealand)" ),
            new("en-PH", "English (Philippines)" ),
            new("en-PK", "English (Pakistan)" ),
            new("en-SA", "English (Saudi Arabia)" ),
            new("en-SG", "English (Singapore)" ),
            new("en-us", "English (United States)" ),
            new("en-xg", "English (Gulf)" ),
            new("en-XN", "English (International)" ),
            new("en-za", "English (South Africa)" ),
            new("eo-XN", "Esperanto" ),
            new("es-ar", "Spanish (Argentina)" ),
            new("es-BO", "Spanish (Bolivia)" ),
            new("es-CL", "Spanish (Chile)" ),
            new("es-CO", "Spanish (Colombia)" ),
            new("es-CR", "Spanish (Costa Rica)" ),
            new("es-CU", "Spanish (Cuba)" ),
            new("es-DO", "Spanish (Dominican Republic)" ),
            new("es-EC", "Spanish (Ecuador)" ),
            new("es-es", "Spanish (Spain)" ),
            new("es-GT", "Spanish (Guatemala)" ),
            new("es-HN", "Spanish (Honduras)" ),
            new("es-mx", "Spanish (Mexico)" ),
            new("es-NI", "Spanish (Nicaragua)" ),
            new("es-PA", "Spanish (Panama)" ),
            new("es-PE", "Spanish (Peru)" ),
            new("es-pr", "Spanish (Puerto Rico)" ),
            new("es-PY", "Spanish (Paraguay)" ),
            new("es-SV", "Spanish (El Salvador)" ),
            new("es-US", "Spanish (United States)" ),
            new("es-UY", "Spanish (Uruguay)" ),
            new("es-VE", "Spanish (Venezuela)" ),
            new("es-XL", "Spanish (Latin America)" ),
            new("es-XN", "Spanish (International)" ),
            new("et-EE", "Estonian" ),
            new("etu-NG", "Ejagham" ),
            new("eu-ES", "Basque" ),
            new("fa-AF", "Dari" ),
            new("fa-in", "Farsi [Persian]" ),
            new("fa-IR", "Persian [Farsi]" ),
            new("fat-GH", "Fanti" ),
            new("fi-FI", "Finnish" ),
            new("fil-PH", "Filipino (Philippines)" ),
            new("fo-FO", "Faroese" ),
            new("fr-011", "French (West and Central Africa)" ),
            new("fr-be", "French (Belgium)" ),
            new("fr-ca", "French (Canada)" ),
            new("fr-CD", "French (DR Congo)" ),
            new("fr-ch", "French (Switzerland)" ),
            new("fr-CI", "French (Ivory Coast)" ),
            new("fr-CM", "French (Cameroon)" ),
            new("fr-DZ", "French (Algeria)" ),
            new("fr-fr", "French (France)" ),
            new("fr-GN", "French (Guinea)" ),
            new("fr-lu", "French (Luxembourg)" ),
            new("fr-MA", "French (Morocco)" ),
            new("fr-QM", "French (Africa)" ),
            new("fr-TG", "French (Togo)" ),
            new("fr-TN", "French (Tunisia)" ),
            new("fr-xn", "French (International)" ),
            new("fuf-GN", "Pular" ),
            new("fy-NL", "Frisian" ),
            new("gaa-GH", "Ga" ),
            new("ga-ie", "Irish" ),
            new("gd-GB", "Gaelic [Scottish]" ),
            new("gil-kir", "Gilbertese (Kiribati)" ),
            new("gl-ES", "Galician [Gallegan]" ),
            new("gu-IN", "Gujarati" ),
            new("gur-GH", "Farefare" ),
            new("ha-NE", "Hausa" ),
            new("he-IL", "Hebrew" ),
            new("hi-FJ", "Hindustani (Fiji)" ),
            new("hi-IN", "Hindi" ),
            new("hil-PH", "Hiligaynon" ),
            new("hmn-LA", "Hmong" ),
            new("ho-PG", "Hiri Motu (Papua New Guinea)" ),
            new("hr-ba", "Croatian (Bosnia and Herzegovina)" ),
            new("hr-HR", "Croatian" ),
            new("ht-HT", "Creole (Haiti)" ),
            new("hu-HU", "Hungarian" ),
            new("hy-AM", "Armenian" ),
            new("hz-na", "Herero" ),
            new("id-ID", "Indonesian [Bahasa]" ),
            new("igb-NG", "Ebira [Igbira]" ),
            new("ig-NG", "Igbo" ),
            new("ike-CA-NU", "Inuktitut (Nunavut)" ),
            new("ike-CA-QC", "Inuktitut (Nunavik)" ),
            new("ilo-PH", "Ilocano [Iloko]" ),
            new("is-IS", "Icelandic" ),
            new("it-CH", "Italian (Switzerland)" ),
            new("it-IT", "Italian (Italy)" ),
            new("its-NG", "Isekiri [Itsekiri]" ),
            new("ja-jp", "Japanese" ),
            new("jam-jm", "Jamaican Patois (Patwa)" ),
            new("jaz-NC", "Jawe" ),
            new("jv-ID", "Javanese" ),
            new("ka-GE", "Georgian" ),
            new("kam-KE", "Kamba" ),
            new("kck-ZW", "Kalanga" ),
            new("kg-CD", "Koongo [Kikongo]" ),
            new("kik-KE", "Kikuyu [Gikuyu]" ),
            new("kk-cn", "Kazakh (China)" ),
            new("kk-KZ", "Kazakh" ),
            new("kl-GL", "Greenlandic [Kalaallisut]" ),
            new("km-KH", "Khmer [Cambodian]" ),
            new("kn-IN", "Kannada" ),
            new("kok-IN", "Konkani" ),
            new("ko-kr", "Korean" ),
            new("kri-SL", "Krio" ),
            new("ks-IN", "Kashmiri" ),
            new("ks-PK", "Kashmiri (Pakistan)" ),
            new("ksw-mymr", "Karen (S’gaw)" ),
            new("ku-IQ", "Kurdish, Central [Sorani]" ),
            new("ku-TR", "Kurdish, Northern [Kurmanji]" ),
            new("ky-KG", "Kirghiz [Kyrgyz]" ),
            new("la-VA", "Latin" ),
            new("lb-LU", "Luxembourgish [Letzeburgesch]" ),
            new("lg-UG", "Luganda" ),
            new("ln-CG", "Lingala" ),
            new("lo-LA", "Lao" ),
            new("loz-ZM", "Lozi" ),
            new("lt-LT", "Lithuanian" ),
            new("lu-CD", "Luba-Lulua [Tshiluba]" ),
            new("luo-ke", "Luo (Dholuo)" ),
            new("lv-LV", "Latvian" ),
            new("mai-IN", "Maithili" ),
            new("mg-MG", "Malagasy" ),
            new("mi-NZ", "Maori" ),
            new("mk-MK", "Macedonian" ),
            new("ml-IN", "Malayalam" ),
            new("mni-IN", "Manipuri [Meitei]" ),
            new("mnk-GM", "Mandinka [Mandingo]" ),
            new("mn-MN", "Mongolian" ),
            new("moh-CA", "Mohawk" ),
            new("mr-IN", "Marathi" ),
            new("ms-MY", "Malay (Malaysia)" ),
            new("ms-SG", "Malay (Singapore)" ),
            new("mt-MT", "Maltese" ),
            new("mtq-vn", "Muong" ),
            new("myi-IN", "Mina (India)" ),
            new("my-MM", "Burmese" ),
            new("myn-GT", "K'iche' [Quiche]" ),
            new("naq-NA", "Nama" ),
            new("nb-NO", "Norwegian [Bokmål]" ),
            new("nd-ZW", "Ndebele, Northern [Sindebele]" ),
            new("ne-NP", "Nepali" ),
            new("nic-GH", "Dagbani" ),
            new("nl-BE", "Dutch (Belgium)" ),
            new("nl-NL", "Dutch (The Netherlands)" ),
            new("nn-NO", "Norwegian [Nynorsk]" ),
            new("nr-ZA", "Ndebele, Southern" ),
            new("nso-ZA", "Sotho, Northern [Pedi, Sepedi]" ),
            new("nv-US", "Navajo" ),
            new("ny-MW", "Nyanja" ),
            new("oc-ES", "Occitan" ),
            new("om-ET", "Oromo" ),
            new("or-IN", "Orya [Oriya]" ),
            new("pag-PH", "Pangasinan" ),
            new("pa-IN", "Panjabi [Punjabi]" ),
            new("pam-PH", "Pampanga (Philippines)" ),
            new("pap-AW", "Papiamento [Papiamentu]" ),
            new("pa-PK", "Punjabi (Pakistan)" ),
            new("pl-PL", "Polish" ),
            new("ps-AF", "Pashto [Pushto]" ),
            new("pt-AO", "Portuguese (Angola)" ),
            new("pt-BR", "Portuguese (Brazil)" ),
            new("pt-MZ", "Portuguese (Mozambique)" ),
            new("pt-PT", "Portuguese (Portugal)" ),
            new("qu-BO", "Quechua" ),
            new("qu-pe", "Quechua (Peru)" ),
            new("rm-CH", "Romansch" ),
            new("roa-IT", "Lombard" ),
            new("ro-MD", "Romanian (Moldova)" ),
            new("rom-MK", "Romani, Vlax (Romania)" ),
            new("ro-RO", "Romanian (Romania)" ),
            new("ru-BY", "Russian (Belarus)" ),
            new("ru-EE", "Russian (Estonia)" ),
            new("ru-IL", "Russian (Israel)" ),
            new("ru-kg", "Russian (Kyrgyzstan)" ),
            new("ru-KZ", "Russian (Kazakhstan)" ),
            new("ru-lt", "Russian (Lithuania)" ),
            new("ru-LV", "Russian (Latvia)" ),
            new("ru-RU", "Russian" ),
            new("ru-UA", "Russian (Ukraine)" ),
            new("ru-xn", "Russian (International)" ),
            new("rw-RW", "Kinyarwanda" ),
            new("sa-IN", "Sanskrit" ),
            new("sat-IN", "Santali" ),
            new("sco-GB", "Scots" ),
            new("sd-PK", "Sindhi" ),
            new("se-NO", "Saami [Lapp]" ),
            new("sgn-GB", "Sign Language, British" ),
            new("shg-BW", "Shua" ),
            new("si-LK", "Sinhala [Sinhalese]" ),
            new("skr-PK", "Saraiki" ),
            new("sk-SK", "Slovak" ),
            new("sl-SI", "Slovenian [Slovene]" ),
            new("sm-WS", "Samoan" ),
            new("sn-ZW", "Shona" ),
            new("so-SO", "Somali" ),
            new("sq-AL", "Albanian" ),
            new("sr-Cyrl-RS", "Serbian [Cyrillic]" ),
            new("sr-Latn-ME", "Serbian [Latin] (Montenegro)" ),
            new("sr-Latn-RS", "Serbian [Latin]" ),
            new("srp-ME", "Montenegrin" ),
            new("sso-LS", "Sissano" ),
            new("ss-SZ", "Swati [Swazi]" ),
            new("st-LS", "Sotho, Southern [Sesotho]" ),
            new("su-ID", "Sundanese" ),
            new("sus-GN", "Susu" ),
            new("sv-FI", "Swedish (Finland)" ),
            new("sv-SE", "Swedish (Sweden)" ),
            new("sw-KE", "Swahili" ),
            new("syl-BD", "Sylheti" ),
            new("ta-IN", "Tamil (India)" ),
            new("ta-LK", "Tamil (Sri Lanka)" ),
            new("tcy-IN", "Tulu" ),
            new("te-IN", "Telugu" ),
            new("tem-SL", "Timne [Themne]" ),
            new("TEO", "Teso (Uganda)" ),
            new("tet-TL", "Tetum" ),
            new("tg-TJ", "Tajik" ),
            new("th-TH", "Thai" ),
            new("ti-ER", "Tigrinya [Tigrigna]" ),
            new("tig-ER", "Tigre" ),
            new("tiv-NG", "Tiv" ),
            new("tk-TM", "Turkmen" ),
            new("tll-CD", "Tetela" ),
            new("tl-PH", "Tagalog" ),
            new("tn-BW", "Tswana [Setswana]" ),
            new("to-TO", "Tongan" ),
            new("tpi-PG", "Tok Pisin (Papua New Guinea)" ),
            new("tr-CY", "Turkish (Cyprus)" ),
            new("tr-TR", "Turkish" ),
            new("ts-ZA", "Tsonga" ),
            new("tt-RU", "Tatar" ),
            new("tvl-TV", "Tuvaluan [Tuvalu]" ),
            new("tw-GH", "Twi" ),
            new("ug-CN", "Uighur [Uyghur]" ),
            new("ug-ny", "Nyankole" ),
            new("uk-UA", "Ukrainian" ),
            new("und-und", "All Languages" ),
            new("ur-IN", "Urdu (India)" ),
            new("ur-PK", "Urdu (Pakistan)" ),
            new("uz-Cyrl-UZ", "Uzbek (Cyrillic)" ),
            new("uz-Latn-UZ", "Uzbek (Latin)" ),
            new("uz-UZ", "Uzbek" ),
            new("ve-ZA", "Venda" ),
            new("vi-VN", "Vietnamese" ),
            new("wo-SN", "Wolof" ),
            new("wuu-CN-CN", "Wu Chinese [Shanghainese]" ),
            new("xh-ZA", "Xhosa" ),
            new("xsm-GH", "Kasem" ),
            new("yao-MW", "Yao" ),
            new("yi-IL", "Yiddish" ),
            new("yo-NG", "Yoruba" ),
            new("zh(-Hans)-MY", "Chinese (Malaysia)" ),
            new("zh-cn", "Chinese [Simplified]" ),
            new("zh-hk", "Chinese (Hong Kong)" ),
            new("zh-mo", "Chinese (Macau)" ),
            new("zh-SG", "Chinese (Singapore)" ),
            new("zh-tw", "Chinese [Traditional]" ),
            new("zh-xy", "Chinese (Cantonese)" ),
            new("zu-ZA", "Zulu" )
        };
    }
}